name: Android CI

on:
  push:
    branches: [ "v2.00" ]
  pull_request:
    branches: [ "v2.00" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload to Release Action
      uses: Shopify/upload-to-release@v1.0.1
      with: 
       name: AI智听-$ {{github.event.release.tag_name}}.apk
       path: app/build/outputs/apk/debug/app-debug.apk
       repo-token: ${{github.token}}
       content-type: application/zip
